# Generated by Django 5.1.6 on 2025-03-19 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_localnewssite'),
        ('fnewsapp', '0002_remove_article_category_article_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accounts.localnewssite'),
        ),
    ]
