# Generated by Django 5.1.6 on 2025-03-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnewsapp', '0003_article_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
